#!/usr/bin/env bash
# Orca worktree delegate for the Pure `backend-api` repo.
# Keyed by the main-checkout basename (backend-api) — run by orca-worktree-setup.sh
# from inside a fresh backend-api worktree, after generic config was linked.
#
# Reuses the pure-dev plugin's agent-worktree-setup.sh as the single source of
# truth for backend-api's compose specifics (shared with the Claude subagent
# flow). That script re-links config idempotently and prints a collision-safe
# `docker compose ... pytest` command to stdout. We persist that command as a
# runnable helper in the worktree's PRIVATE git dir so it never shows in
# `git status`, and print where it landed.
#
# Non-fatal on every path — the dispatcher must never be blocked. Do NOT `set -e`.

log() { echo "orca-worktree.d/backend-api: $*" >&2; }

pure_dev="$HOME/pure/claude-plugins/plugins/pure-dev/skills/worktree-agent/scripts/agent-worktree-setup.sh"

if [ ! -f "$pure_dev" ]; then
  log "pure-dev script not found at $pure_dev; config already linked by dispatcher, skipping test-command emit"
  exit 0
fi

# Run the pure-dev script, capturing its stdout (the test command). Its own
# symlink step re-runs harmlessly (idempotent). If it fails (e.g. not in a work
# tree), degrade gracefully instead of writing a partial helper.
if ! cmd=$(bash "$pure_dev"); then
  log "WARN: pure-dev script exited nonzero; not writing run-tests helper"
  exit 0
fi

# Persist the command to the per-worktree private git dir (never in `git status`).
# Absolutize --git-dir defensively (it's already absolute in a linked worktree).
git_dir=$(git rev-parse --git-dir 2>/dev/null) || git_dir=""
if [ -z "$git_dir" ]; then
  log "WARN: could not resolve git dir; printing command only"
  printf '%s\n' "$cmd"
  exit 0
fi
case "$git_dir" in
  /* | [A-Za-z]:* ) : ;;
  * ) git_dir=$(cd "$git_dir" && pwd) ;;
esac

helper_dir="$git_dir/orca"
helper="$helper_dir/run-tests.sh"
if mkdir -p "$helper_dir"; then
  {
    printf '#!/usr/bin/env bash\n'
    printf '# Auto-generated by orca-worktree.d/backend-api.sh — run this worktree'\''s tests\n'
    printf '# against the reused base stack with namespaced DBs. Regenerated on each spawn.\n'
    printf 'set -euo pipefail\n'
    printf '%s\n' "$cmd"
  } >"$helper" && chmod +x "$helper" \
    && log "wrote test helper: $helper" \
    || log "WARN: failed to write $helper"
else
  log "WARN: could not create $helper_dir"
fi

# Print the helper path + the command to stdout for Orca / the developer.
echo "run this worktree's tests with:"
echo "  $helper"
echo "or directly:"
printf '%s\n' "$cmd"
exit 0
